-------------------------------------------Drop tables
DROP TABLE Jezero CASCADE CONSTRAINTS ;
DROP TABLE Zvire CASCADE CONSTRAINTS ;
DROP TABLE Kvetina CASCADE CONSTRAINTS ;
DROP TABLE Kotec CASCADE CONSTRAINTS ;
DROP TABLE Zahon CASCADE CONSTRAINTS ;
DROP TABLE Stezka CASCADE CONSTRAINTS ;